---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret
type: Opaque
data:
  username: QURNSU4K
  password: aGFsZXItdmVzdC1oYWwK
---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost
spec:
  online: true
  bmc:
    address: ipmi://192.168.20.11
    credentialsName: example-baremetalhost-secret
  bootMACAddress: ac:1f:6b:12:65:34
---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret1
type: Opaque
data:
  username: QURNSU4K
  password: aGFsZXItdmVzdC1oYWwK
---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost1
spec:
  online: true
  bmc:
    address: ipmi://192.168.20.12
    credentialsName: example-baremetalhost-secret1
  bootMACAddress: 0c:c4:7a:ca:3b:2c
---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret2
type: Opaque
data:
  username: QURNSU4K
  password: aGFsZXItdmVzdC1oYWwK
---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost2
spec:
  online: true
  bmc:
    address: ipmi://192.168.20.13
    credentialsName: example-baremetalhost-secret2
  bootMACAddress: 0c:c4:7a:9a:3c:cc

